nohup: ignoring input
2021-01-25 22:20:30.197600: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-01-25 22:20:30.197642: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
wandb: Currently logged in as: kjappelbaum (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.10.15 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.10.12
wandb: Syncing run celestial-sun-3397
wandb: ‚≠êÔ∏è View project at https://wandb.ai/kjappelbaum/ga_replication_study
wandb: üöÄ View run at https://wandb.ai/kjappelbaum/ga_replication_study/runs/1t7b5pzs
wandb: Run data is saved locally in /home/kjablonk/documents/replication_study/selfies_ga_nn_replication/wandb/run-20210125_222031-1t7b5pzs
wandb: Run `wandb offline` to turn off syncing.

{'beta': 1000.0, 'alphabet': 'original', 'num_generations': 200, 'generation_size': 500, 'max_molecules_len': 81, 'disc_epochs_per_generation': 10, 'disc_enc_type': 'properties_rdkit', 'disc_layers': [100, 51], 'training_start_gen': 0, 'properties_calc_ls': ['logP', 'SAS', 'RingP']}
###   On generation 1 of 200
Traceback (most recent call last):
  File "/home/kjablonk/anaconda3/envs/replication_study/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kjablonk/anaconda3/envs/replication_study/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kjablonk/documents/replication_study/selfies_ga_nn_replication/experiments/guacamol_baseline/benchmarks/goal_benchmark_rev_ga_original.py", line 365, in <module>
    cli()
  File "/home/kjablonk/anaconda3/envs/replication_study/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kjablonk/anaconda3/envs/replication_study/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kjablonk/anaconda3/envs/replication_study/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kjablonk/anaconda3/envs/replication_study/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kjablonk/documents/replication_study/selfies_ga_nn_replication/experiments/guacamol_baseline/benchmarks/goal_benchmark_rev_ga_original.py", line 359, in cli
    assess_goal_directed_generation(
  File "/home/kjablonk/anaconda3/envs/replication_study/lib/python3.8/site-packages/guacamol/assess_goal_directed_generation.py", line 31, in assess_goal_directed_generation
    results = _evaluate_goal_directed_benchmarks(
  File "/home/kjablonk/anaconda3/envs/replication_study/lib/python3.8/site-packages/guacamol/assess_goal_directed_generation.py", line 64, in _evaluate_goal_directed_benchmarks
    result = benchmark.assess_model(goal_directed_molecule_generator)
  File "/home/kjablonk/anaconda3/envs/replication_study/lib/python3.8/site-packages/guacamol/goal_directed_benchmark.py", line 70, in assess_model
    molecules = model.generate_optimized_molecules(scoring_function=self.wrapped_objective,
  File "/home/kjablonk/documents/replication_study/selfies_ga_nn_replication/experiments/guacamol_baseline/benchmarks/goal_benchmark_rev_ga_original.py", line 274, in generate_optimized_molecules
    best_smiles = initiate_ga(
  File "/home/kjablonk/documents/replication_study/selfies_ga_nn_replication/experiments/guacamol_baseline/benchmarks/goal_benchmark_rev_ga_original.py", line 100, in initiate_ga
    ) = gen_func.obtain_fitness(
  File "/home/kjablonk/documents/replication_study/selfies_ga_nn_replication/experiments/guacamol_baseline/benchmarks/generation_props_original.py", line 114, in obtain_fitness
    (fitness_here, scores, discriminator_predictions, _) = fitness(
  File "/home/kjablonk/documents/replication_study/selfies_ga_nn_replication/experiments/guacamol_baseline/benchmarks/generation_props_original.py", line 74, in fitness
    max_fitness_collector.append(np.max(scor∆íes))
NameError: name 'scor∆íes' is not defined
wandb: Waiting for W&B process to finish, PID 12185
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb: - 0.01MB of 0.01MB uploaded (0.00MB deduped)wandb: \ 0.02MB of 0.02MB uploaded (0.00MB deduped)wandb:                                                                                
wandb: Find user logs for this run at: /home/kjablonk/documents/replication_study/selfies_ga_nn_replication/wandb/run-20210125_222031-1t7b5pzs/logs/debug.log
wandb: Find internal logs for this run at: /home/kjablonk/documents/replication_study/selfies_ga_nn_replication/wandb/run-20210125_222031-1t7b5pzs/logs/debug-internal.log
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
wandb: 
wandb: Synced celestial-sun-3397: https://wandb.ai/kjappelbaum/ga_replication_study/runs/1t7b5pzs

